[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
dependencies = ["build-frontend", "build-backend"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.serve-frontend]
dependencies = [{ name = "serve", path = "frontend" }]

[tasks.build-frontend]
dependencies = [{ name = "build", path = "frontend" }]

[tasks.serve-backend]
install_crate = "cargo-watch"
command = "cargo"
args = ["watch", "-w", "backend", "-w", "src", "-x", "run", "-c"]
