[tasks.format]

[tasks.clean]

[tasks.test]

[tasks.serve-frontend]
workspace = false
dependencies = [{ name = "serve", path = "frontend" }]

[tasks.serve-backend]
workspace = false
install_crate = "cargo-watch"
command = "cargo"
args = ["watch", "-w", "backend", "-w", "src", "-x", "run", "-c"]

[tasks.build]
workspace = false
dependencies = [{ name = "build", path = "frontend" }]
install_crate = "cargo-watch"
command = "cargo"
args = ["build", "--release"]
