[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]
dependencies = [{ name = "clean" }, { name = "build", path = "../frontend" }]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.serve]
install_crate = "cargo-watch"
command = "cargo"
args = ["watch", "-w", "../src", "-w", "src", "-x", "run", "-c"]
dependencies = [{ name = "build", path = "../frontend" }]
